name: gts aurorafin
on:
  schedule:
    - cron: "00 07 * * 0" # 07:00 UTC every Sunday
  workflow_dispatch:
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - images/aurora/aurora-dx--gts.yml
          - images/aurora/aurora--gts.yml
          - images/bluefin/bluefin-dx--gts.yml
          - images/bluefin/bluefin--gts.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          use_unstable_cli: true
